[package]
name = "jack-in"
description = "an experimental sliding sync/syncv3 terminal client to jack into the matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17"
crossterm = "0.22"
matrix-sdk = { path = "../../crates/matrix-sdk" }
structopt = "0.3"
