[package]
name = "matrix-sdk-ffi"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ffi"]
license = "Apache-2.0"
readme = "README.md"
rust-version = "1.56"
repository = "https://github.com/matrix-org/matrix-rust-sdk"

[lib]
crate-type = ["cdylib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["with-runtime"]
with-runtime = [
    "tokio"
]

[build-dependencies]
uniffi_build = { version = "0.17.0",  features = [ "builtin-bindgen" ]}

[dependencies]
uniffi = { version = "0.17.0" }
uniffi_macros = { version = "0.17.0" }
matrix-sdk = { path = "../matrix-sdk", default-features = false, features = ["sled_state_store", "native-tls"] }
tokio = { version = "1", optional = true, features = ["rt-multi-thread", "macros"] }
sanitize-filename-reader-friendly = "2.2.1"
anyhow = "1.0.51"
futures = "0.3.17"
lazy_static = "1.4"
parking_lot = "0.11.2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
derive_builder = "0.10.2"
url = "2.2.2"
thiserror = "1.0.30"